openapi: 3.0.0
info:
  title: Ejemplo API
  description: Documentación de ejemplo para una API
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
paths:
  /users:
    get:
      summary: Obtiene la lista de usuarios
      description: Devuelve una lista de todos los usuarios.
      responses:
        '200':
          description: Éxito. Devuelve la lista de usuarios.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Categoria'
components:
  schemas:
    Categoria:
      type: object
      properties:
        id_categoria:
          type: integer
          format: int64
          description: ID de la categoria.
        nombre:
          type: string
          description: Nombre de de la categoria.
        descripcion:
          type: string
          description: Descripcion de la categoria.
    Marca:
      type: object
      properties:
        id_marca:
          type: integer
          format: int64 
